# Generated by Django 4.1.3 on 2022-11-22 00:30

import Profile.models.profile
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(max_length=255)),
                ('email', models.URLField(max_length=255)),
                ('twitter', models.URLField(max_length=255)),
                ('linkedin', models.URLField(max_length=255)),
                ('instagram', models.URLField(max_length=255)),
                ('github', models.URLField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(null=True, upload_to=Profile.models.profile.upload_profile_location),
        ),
    ]
